apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
allowVolumeExpansion: true
allowedTopologies: []
mountOptions: []
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
