apiVersion: v1
kind: Service
metadata:
    name: arangodb-ingress-proxy
    namespace: development
    labels:
        app.kubernetes.io/name: arangodb-ingress-proxy
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
spec:
    ports:
        - name: server
          protocol: TCP
          port: 443
          targetPort: 443
          nodePort: 32369
    selector:
        app.kubernetes.io/name: arangodb-ingress-proxy
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
    type: LoadBalancer
