apiVersion: v1
kind: Secret
metadata:
  name: arangodb
  namespace: development
  labels:
    app.kubernetes.io/instance: arango
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arango
type: Opaque
data:
  root-password: SW92NENVb21PZw==
